[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  # Any request to /api/* will be server‐side fetched from your HTTP backend
  from = "/*"
  to = "http://65.1.86.250:8000/:splat"
  status = 200      # serve as a proxy (200, not a 301/302)
  force = true      # override any existing file matching

[[redirects]]
  from    = "/index.html"
  to      = "/index.html"
  status  = 200
